### ISSUE TITLE
report a managed csv status in the storagesystem status

### ISSUE THREAD

**Issue by iamniting** [red-hat-storage/odf-operator#23]
Creating an issue to discuss this further.

Questions:
- should we report the status of storagecluster and flashsystemcluster both?
- What fields should I report?
- or should I just report CSV-name and namespace instead so one can look at the CSV status directly?

example status of CSV for second question:
```
status:
  conditions:
  - lastTransitionTime: "2021-07-07T10:50:09Z"
    lastUpdateTime: "2021-07-07T10:50:09Z"
    message: Webhook rules cannot include the OLM group
    phase: Failed
    reason: InvalidWebhookDescription
  - lastTransitionTime: "2021-07-07T10:50:09Z"
    lastUpdateTime: "2021-07-07T10:50:09Z"
    message: calculated deployment install is bad
    phase: Pending
    reason: NeedsReinstall
  - lastTransitionTime: "2021-07-07T10:50:09Z"
    lastUpdateTime: "2021-07-07T10:50:09Z"
    message: Webhook rules cannot include the OLM group
    phase: Failed
    reason: InvalidWebhookDescription
  - lastTransitionTime: "2021-07-07T10:50:10Z"
    lastUpdateTime: "2021-07-07T10:50:10Z"
    message: calculated deployment install is bad
    phase: Pending
    reason: NeedsReinstall
  - lastTransitionTime: "2021-07-07T10:50:10Z"
    lastUpdateTime: "2021-07-07T10:50:10Z"
    message: Webhook rules cannot include the OLM group
    phase: Failed
    reason: InvalidWebhookDescription
  - lastTransitionTime: "2021-07-07T10:50:10Z"
    lastUpdateTime: "2021-07-07T10:50:10Z"
    message: calculated deployment install is bad
    phase: Pending
    reason: NeedsReinstall
  - lastTransitionTime: "2021-07-07T10:50:11Z"
    lastUpdateTime: "2021-07-07T10:50:11Z"
    message: Webhook rules cannot include the OLM group
    phase: Failed
    reason: InvalidWebhookDescription
  - lastTransitionTime: "2021-07-07T10:50:11Z"
    lastUpdateTime: "2021-07-07T10:50:11Z"
    message: calculated deployment install is bad
    phase: Pending
    reason: NeedsReinstall
  - lastTransitionTime: "2021-07-07T10:50:11Z"
    lastUpdateTime: "2021-07-07T10:50:11Z"
    message: Webhook rules cannot include the OLM group
    phase: Failed
    reason: InvalidWebhookDescription
  - lastTransitionTime: "2021-07-07T10:50:11Z"
    lastUpdateTime: "2021-07-07T10:50:11Z"
    message: calculated deployment install is bad
    phase: Pending
    reason: NeedsReinstall
  - lastTransitionTime: "2021-07-07T10:50:11Z"
    lastUpdateTime: "2021-07-07T10:50:11Z"
    message: Webhook rules cannot include the OLM group
    phase: Failed
    reason: InvalidWebhookDescription
  - lastTransitionTime: "2021-07-07T10:50:11Z"
    lastUpdateTime: "2021-07-07T10:50:11Z"
    message: calculated deployment install is bad
    phase: Pending
    reason: NeedsReinstall
  - lastTransitionTime: "2021-07-07T10:50:12Z"
    lastUpdateTime: "2021-07-07T10:50:12Z"
    message: Webhook rules cannot include the OLM group
    phase: Failed
    reason: InvalidWebhookDescription
  - lastTransitionTime: "2021-07-07T10:50:12Z"
    lastUpdateTime: "2021-07-07T10:50:12Z"
    message: calculated deployment install is bad
    phase: Pending
    reason: NeedsReinstall
  - lastTransitionTime: "2021-07-07T10:50:12Z"
    lastUpdateTime: "2021-07-07T10:50:12Z"
    message: Webhook rules cannot include the OLM group
    phase: Failed
    reason: InvalidWebhookDescription
  - lastTransitionTime: "2021-07-07T10:50:12Z"
    lastUpdateTime: "2021-07-07T10:50:12Z"
    message: calculated deployment install is bad
    phase: Pending
    reason: NeedsReinstall
  - lastTransitionTime: "2021-07-07T10:50:13Z"
    lastUpdateTime: "2021-07-07T10:50:13Z"
    message: Webhook rules cannot include the OLM group
    phase: Failed
    reason: InvalidWebhookDescription
  - lastTransitionTime: "2021-07-07T10:50:13Z"
    lastUpdateTime: "2021-07-07T10:50:13Z"
    message: calculated deployment install is bad
    phase: Pending
    reason: NeedsReinstall
  - lastTransitionTime: "2021-07-07T10:50:13Z"
    lastUpdateTime: "2021-07-07T10:50:13Z"
    message: Webhook rules cannot include the OLM group
    phase: Failed
    reason: InvalidWebhookDescription
  - lastTransitionTime: "2021-07-07T10:50:13Z"
    lastUpdateTime: "2021-07-07T10:50:13Z"
    message: calculated deployment install is bad
    phase: Pending
    reason: NeedsReinstall
  lastTransitionTime: "2021-07-07T10:50:13Z"
  lastUpdateTime: "2021-07-07T10:50:13Z"
  message: calculated deployment install is bad
  phase: Pending
  reason: NeedsReinstall
  requirementStatus:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    message: CRD is present and Established condition is true
    name: storagesystems.odf.openshift.io
    status: Present
    uuid: 885e8c85-c656-4f33-ab33-b6b00f2c08f7
    version: v1
  - dependents:
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: namespaced rule:{"verbs":["get","list","watch","create","update","patch","delete"],"apiGroups":[""],"resources":["configmaps"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: namespaced rule:{"verbs":["get","list","watch","create","update","patch","delete"],"apiGroups":["coordination.k8s.io"],"resources":["leases"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: namespaced rule:{"verbs":["create","patch"],"apiGroups":[""],"resources":["events"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["create","get","list","update","watch"],"apiGroups":["apiextensions.k8s.io"],"resources":["customresourcedefinitions"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["*"],"apiGroups":["console.openshift.io"],"resources":["consolequickstarts"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["create","delete","get","list","patch","update","watch"],"apiGroups":["odf.openshift.io"],"resources":["storagesystems"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["update"],"apiGroups":["odf.openshift.io"],"resources":["storagesystems/finalizers"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["get","patch","update"],"apiGroups":["odf.openshift.io"],"resources":["storagesystems/status"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["create","delete","get","list","patch","update","watch"],"apiGroups":["operators.coreos.com"],"resources":["catalogsources"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["create","delete","get","list","patch","update","watch"],"apiGroups":["operators.coreos.com"],"resources":["subscriptions"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["create"],"apiGroups":["authentication.k8s.io"],"resources":["tokenreviews"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["create"],"apiGroups":["authorization.k8s.io"],"resources":["subjectaccessreviews"]}
      status: Satisfied
      version: v1
    group: ""
    kind: ServiceAccount
    message: ""
    name: odf-operator-controller-manager
    status: Present
    version: v1

```
