### ISSUE TITLE
Default PVC Mount Permissions Changed?

### ISSUE THREAD

**Issue by Joshua-Beha** [red-hat-storage/odf-operator#324]
In the course of deploying an application to an OpenShift 4.12 cluster, I came across an issue trying to mount a PVC from ODF (operator version 4.12.4-rhodf). Upon further inspection, it looks like the PVC was mounted to the pod with 755 permissions. This was problematic as I was trying to run with UID 1000 *without* giving `privileged` access.
As a comparison, I tried the same test on an OCP 4.10 cluster (running ODF operator version 4.10.13). It looks like the PVC was then mounted with 777 permissions.
Is there a reason for this difference in behaviors? Was it something I missed in the ODF documentation? I tried with a storageclass not provided by ODF and saw no difference in behavior across the two OCP clusters.

Below is some test yaml that I used:
```
kind: Pod
apiVersion: v1
metadata:
  name: test-pod-cephfs-uid1000
spec:
  containers:
  - name: test-pod-cephfs-uid1000
    image: busybox:latest
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "whoami && touch /mnt/SUCCESS && echo \"Success\" && exit 0 || exit 1"
    volumeMounts:
      - name: cephfs-pvc-uid1000
        mountPath: "/mnt"
    securityContext:
      runAsUser: 1000
  restartPolicy: "Never"
  volumes:
    - name: cephfs-pvc-uid1000
      persistentVolumeClaim:
        claimName: test-claim-cephfs-uid1000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim-cephfs-uid1000
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
```
